# src/main/resources/application.properties

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=tu_usuario
quarkus.datasource.password=tu_password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/tu_base_datos

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Configuración JWT (ejemplo básico)
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.proactive=true
quarkus.http.auth.form.enabled=false