# Database
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=66138627
quarkus.datasource.jdbc.url=${MYSQL_URL:jdbc:mysql://localhost:3306/usuarios_quarkus}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# JWT Configuration
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=maximiliano-administrador-api
smallrye.jwt.sign.key.location=privateKey.pem

# App Security (custom)
app.security.jwt.issuer=maximiliano-administrador-api
app.security.jwt.expiration=3600

# Logging
quarkus.log.level=INFO
quarkus.log.category."ejemplo.quarkus".level=DEBUG
